language: node_js
node_js:
  - "stable"
  - "7.6.0"
install:
  - npm install
  - npm install -g gulp@3.9.1
  - npm install gulp-eslint@3.*
  - npm install gulp-mocha@4.*
  - npm install chai@4.*
script:
  - gulp --gulpfile node_modules/fepper/tasker.js test
