language: node_js
node_js:
  - "stable"
  - "7.6.0"
install:
  - npm install
  - npm install -g gulp@3.9.1
  - npm install gulp-eslint@3.0.1
  - npm install gulp-mocha@4.3.1
  - npm install chai@4.0.2
script:
  - gulp --gulpfile node_modules/fepper/tasker.js test
